### ISSUE TITLE
I can't build with cocoapods by gradle.

### ISSUE THREAD

**Issue by shiratsu** [openbakery/gradle-xcodePlugin#152]
Hi,there

I'm sorry for contacting suddenly.
I want to build my project with cocoapods by gradle.
if not to use cocoapods project,it can build.
However if to use cocoapods,it can't build.

build.gradle is below.
```
buildscript {
repositories {
  maven {
    url('http://openbakery.org/repository/')
  }
  mavenCentral()
}
dependencies {
  classpath group: 'org.openbakery', name: 'xcodePlugin', version: '0.10.+'
}
}

apply plugin: 'xcode'

xcodebuild {
target = 'NeoCafesagashi'
workspace = 'NeoCafesagashi.xcworkspace'
}

task wrapper(type: Wrapper) {
gradleVersion = '1.10'
}
``` 
if i run below command,it will occur below error
```
% gradle xcodebuild --stacktrace
:cocoapods
Skipping installing pods, because the Pods directory already exists
:xcodebuildConfig
:infoplistModify
Updating /Users/shiratsu/Documents/NeoCafesagashi/NeoCafesagashi/NeoCafesagashi-Info.plist
:keychainClean
:keychainCreate SKIPPED
:provisioningClean
:provisioningInstall SKIPPED
:xcodebuild FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':xcodebuild'.
> Command failed to run (exit code 65): 'xcodebuild -configuration Debug -sdk iphonesimulator -target NeoCafesagashi DSTROOT=/Users/shiratsu/Documents/NeoCafesagashi/build/dst OBJROOT=/Users/shiratsu/Documents/NeoCafesagashi/build/obj SYMROOT=/Users/shiratsu/Documents/NeoCafesagashi/build/sym SHARED_PRECOMPS_DIR=/Users/shiratsu/Documents/NeoCafesagashi/build/shared'

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':xcodebuild'.
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
    at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
    at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
    at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
    at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
    at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
    at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
    at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
    at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:305)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
    at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
    at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
    at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
    at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
    at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
    at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
    at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
    at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
    at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
    at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
    at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
    at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
    at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
    at org.gradle.launcher.cli.RunBuildAction.run(RunBuildAction.java:51)
    at org.gradle.internal.Actions$RunnableActionAdapter.execute(Actions.java:171)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:237)
    at org.gradle.launcher.cli.CommandLineActionFactory$ParseAndBuildAction.execute(CommandLineActionFactory.java:210)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:35)
    at org.gradle.launcher.cli.JavaRuntimeValidationAction.execute(JavaRuntimeValidationAction.java:24)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:206)
    at org.gradle.launcher.cli.CommandLineActionFactory$WithLogging.execute(CommandLineActionFactory.java:169)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:33)
    at org.gradle.launcher.cli.ExceptionReportingAction.execute(ExceptionReportingAction.java:22)
    at org.gradle.launcher.Main.doAction(Main.java:33)
    at org.gradle.launcher.bootstrap.EntryPoint.run(EntryPoint.java:45)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.runNoExit(ProcessBootstrap.java:54)
    at org.gradle.launcher.bootstrap.ProcessBootstrap.run(ProcessBootstrap.java:35)
    at org.gradle.launcher.GradleMain.main(GradleMain.java:23)
Caused by: org.openbakery.CommandRunnerException: Command failed to run (exit code 65): 'xcodebuild -configuration Debug -sdk iphonesimulator -target NeoCafesagashi DSTROOT=/Users/shiratsu/Documents/NeoCafesagashi/build/dst OBJROOT=/Users/shiratsu/Documents/NeoCafesagashi/build/obj SYMROOT=/Users/shiratsu/Documents/NeoCafesagashi/build/sym SHARED_PRECOMPS_DIR=/Users/shiratsu/Documents/NeoCafesagashi/build/shared'
    at org.openbakery.CommandRunner.run(CommandRunner.groovy:88)
    at org.openbakery.XcodeBuildTask.xcodebuild(XcodeBuildTask.groovy:53)
    at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
    at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:579)
    at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:562)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
    at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
    ... 44 more


BUILD FAILED

Total time: 7.531 secs
```
How do i do about it?

**Comment by shiratsu** [comment]
I'm sorry.I could resolve by myself.
I tryed to run command which i got from stack trace error.
I had been fixing while i was watching error on command line.

Finally i could build by below gradle file
```
buildscript {
  repositories {
    maven {
      url('http://openbakery.org/repository/')
    }
    mavenCentral()
  }
  dependencies {
    classpath group: 'org.openbakery', name: 'xcodePlugin', version: '0.10.+'
  }
}
apply plugin: 'xcode'

xcodebuild {
  target = "NeoCafesagashi"
  scheme = "NeoCafesagashi"
  workspace = "NeoCafesagashi.xcworkspace"
}
```

Thank you!

**Comment by renep** [comment]
You can always run gradle with the '-i' parameter and you see the xcodebuild output that should give you more infos.

**Comment by shiratsu** [comment]
Yeah.I know.But i could not more info by '-i' parameter.
It is also same by '--stacktrace'.
if i will have other question,i wll question.
Thank you!
