### ISSUE TITLE
Appledoc fails with exception

### ISSUE THREAD

**Issue by emartynov** [openbakery/gradle-xcodePlugin#167]
I have java 8 as default JDK. When I try to run `appledoc` command I get next output:
```
java.lang.ClassCastException: org.apache.xerces.parsers.XIncludeAwareParserConfiguration cannot be cast to org.apache.xerces.xni.parser.XMLParserConfiguration
```

**Comment by renep** [comment]
I have Java 8 too but appledoc runs fine on my box. 
Can you provide a full stack trace and a log with 'gradle appledoc --debug`

**Comment by emartynov** [comment]
Here is stacktrace:
```
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':appledoc'.
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
	at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
	at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
	at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
	at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:42)
	at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
	at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
	at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
	at org.gradle.api.internal.AbstractTask.executeWithoutThrowingTaskFailure(AbstractTask.java:306)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.executeTask(AbstractTaskPlanExecutor.java:79)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:63)
	at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:51)
	at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:23)
	at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:88)
	at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:29)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.access$200(DefaultBuildExecuter.java:23)
	at org.gradle.execution.DefaultBuildExecuter$2.proceed(DefaultBuildExecuter.java:68)
	at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:62)
	at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:55)
	at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:149)
	at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
	at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:86)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter$DefaultBuildController.run(InProcessBuildActionExecuter.java:80)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:33)
	at org.gradle.launcher.cli.ExecuteBuildAction.run(ExecuteBuildAction.java:24)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:36)
	at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
	at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:48)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:37)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
	at org.gradle.util.Swapper.swap(Swapper.java:38)
	at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.DaemonHealthTracker.execute(DaemonHealthTracker.java:47)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:71)
	at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.health.HintGCAfterBuild.execute(HintGCAfterBuild.java:41)
	at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
	at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
	at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:246)
	at org.gradle.internal.concurrent.DefaultExecutorFactory$StoppableExecutorImpl$1.run(DefaultExecutorFactory.java:64)
Caused by: : java.lang.ClassCastException: org.apache.xerces.parsers.XIncludeAwareParserConfiguration cannot be cast to org.apache.xerces.xni.parser.XMLParserConfiguration
	at org.openbakery.appledoc.AppledocTask.documentation(AppledocTask.groovy:38)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:63)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:218)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:211)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:200)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
	... 56 more
Caused by: java.lang.ClassCastException: org.apache.xerces.parsers.XIncludeAwareParserConfiguration cannot be cast to org.apache.xerces.xni.parser.XMLParserConfiguration
	at org.apache.xerces.parsers.SAXParser.<init>(Unknown Source)
	at org.apache.xerces.parsers.SAXParser.<init>(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl$JAXPSAXParser.<init>(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserImpl.<init>(Unknown Source)
	at org.apache.xerces.jaxp.SAXParserFactoryImpl.newSAXParser(Unknown Source)
	at org.apache.tools.ant.util.JAXPUtils.newSAXParser(JAXPUtils.java:215)
	at org.apache.tools.ant.util.JAXPUtils.getNamespaceXMLReader(JAXPUtils.java:172)
	at org.apache.tools.ant.helper.ProjectHelper2.parse(ProjectHelper2.java:244)
	at org.apache.tools.ant.helper.ProjectHelper2.parseUnknownElement(ProjectHelper2.java:130)
	at org.apache.tools.ant.helper.ProjectHelper2.parseAntlibDescriptor(ProjectHelper2.java:110)
	at org.apache.tools.ant.taskdefs.Antlib.createAntlib(Antlib.java:91)
	at org.apache.tools.ant.taskdefs.Definer.loadAntlib(Definer.java:425)
	at org.apache.tools.ant.taskdefs.Definer.execute(Definer.java:277)
	at org.apache.tools.ant.ComponentHelper.checkNamespace(ComponentHelper.java:874)
	at org.apache.tools.ant.ComponentHelper.getDefinition(ComponentHelper.java:307)
	at org.apache.tools.ant.ComponentHelper.createComponent(ComponentHelper.java:284)
	at org.apache.tools.ant.ComponentHelper.createComponent(ComponentHelper.java:263)
	at org.apache.tools.ant.UnknownElement.makeObject(UnknownElement.java:429)
	at org.apache.tools.ant.UnknownElement.maybeConfigure(UnknownElement.java:163)
	... 65 more
```

**Comment by emartynov** [comment]
Looks like I have different ant version

**Comment by renep** [comment]
Can you try version 0.10.3-test1, because I think I have found what causes the problem.

What gradle version are you using?

**Comment by emartynov** [comment]
Should I use another repository to download 0.10.3-test1? I use gradle 2.3

**Comment by renep** [comment]
No, I have updated it to my default repo. With the "-test1" it does not download when having "0.10.+' in the config.

**Comment by emartynov** [comment]
Thanks. It fails now with another error:
```
aused by: org.openbakery.CommandRunnerException: Command failed to run (exit code 139): '/Users/emartynov/Development/Projects/MindDistrict/ios-minddistrict/build/documentation/appledoc --print-settings --output /Users/emartynov/Development/Projects/MindDistrict/ios-minddistrict/build/documentation --ignore /Users/emartynov/Development/Projects/MindDistrict/ios-minddistrict/build .'
```

But I think it is related to my appledoc config. Will investigate. Thanks!

**Comment by emartynov** [comment]
Maybe another question. Why do you call appledoc with parameters different from AppledocSettings.plist?

**Comment by renep** [comment]
Let me know if it works, because than I can release a 0.10.3.1 bugfix release ;)

**Comment by renep** [comment]
I only add these parameters:
`--print-settings` This is only a info parameter (I can't remember why I left it there, maybe I should remove it)
`--output`-> so that the output gets to build/appledoc
`--ignore` -> ignore the build directory

**Comment by emartynov** [comment]
Understood. But is this `--ignore` appended to options in plist or replaces them?

**Comment by emartynov** [comment]
You also add folder where to run appledoc - `.`. It pickups all my pods, so it means it ignores my plist setting.

**Comment by emartynov** [comment]
I run appledoc from command line and I see next error:
```
 terminated by signal SIGSEGV (Address boundary error)
```

But it fails on one of Pods file. So might be workaround for me will be somehow remove pods from doc generation

**Comment by renep** [comment]
I have removed the --igore, therefor the plist settings should be tasken. I have overriden the 0.10.3-test1, to run gradle with '--refresh-dependencies' and try again.

**Comment by emartynov** [comment]
Thanks for help!

I see next error now:
```
ERROR: AppledocException: At least one directory or file name path is required, use 'appledoc --help'
```

So '.' is required and might be configured as parameter further

**Comment by renep** [comment]
try again

**Comment by emartynov** [comment]
Cool! It worked but commandline returns exit code 1 and it fails task.

**Comment by emartynov** [comment]
In case if someone has build failure because of appledoc returns 1. Then you have two potions:
 1. Fix all warnings
 2. Run appledoc  --exit-threshold=2

**Comment by renep** [comment]
I prefer option 1 ;-)
I also have "Treat warnings as error" option on in my projects.

Nevertheless, I think if I add the `--exit-threshold=2` then it would be good to have a config option to turn this on. e.g.
```
appledoc {
  ignoreWarnings = true
}
```

**Comment by emartynov** [comment]
Rene, up to you. Would be helpful maybe for someone.

As for me it was experiment if I can get documentation generation done. The result is quite useless right now. I think fixing warning and documenting code better should make it better.

Thanks for useful plugin!

**Comment by renep** [comment]
I have created a new issue #170
Also on my list ist #171
