### ISSUE TITLE
Possible problem with CommandRunner memory

### ISSUE THREAD

**Issue by BamX** [openbakery/gradle-xcodePlugin#222]
I've just received this error and build has stuck(not failed).
```
[15:51:06][Step 2/4] :xcodebuild (running for 5m:13s)
[15:52:22][:xcodebuild] Exception in thread "Thread-20" java.lang.OutOfMemoryError: Java heap space
[15:52:22][:xcodebuild] 	at java.util.Arrays.copyOf(Arrays.java:2367)
[15:52:22][:xcodebuild] 	at java.lang.AbstractStringBuilder.expandCapacity(AbstractStringBuilder.java:130)
[15:52:22][:xcodebuild] 	at java.lang.AbstractStringBuilder.ensureCapacityInternal(AbstractStringBuilder.java:114)
[15:52:22][:xcodebuild] 	at java.lang.AbstractStringBuilder.append(AbstractStringBuilder.java:415)
[15:52:22][:xcodebuild] 	at java.lang.StringBuilder.append(StringBuilder.java:132)
[15:52:22][:xcodebuild] 	at java_lang_StringBuilder$append.call(Unknown Source)
[15:52:22][:xcodebuild] 	at org.openbakery.CommandRunner$1.run(CommandRunner.groovy:134)
[15:52:22][:xcodebuild] 	at java.lang.Thread.run(Thread.java:724)
```
What do you think about it?

**Comment by renep** [comment]
can you try 0.12.4-TEST that I have put on repository.openbakery.org

**Comment by BamX** [comment]
It's working well, thank you
