### ISSUE TITLE
Archive task failed after upgrade to 0.14.4.develop.70

### ISSUE THREAD

**Issue by Aswini999** [openbakery/gradle-xcodePlugin#317]
Error in Console:

```
:provisioningClean
:provisioningInstall
:cocoapodsInstall
:xcodebuildConfig
:infoplistModify
:xcodebuild
Done
:archive FAILED

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':archive'.
> No signature of method: org.openbakery.util.PlistHelper.getValueFromPlist() is applicable for argument types: (java.lang.String, java.lang.String) values: [MyAppTests/MyAppTests-Info.plist, CFBundleIdentifier]
  Possible solutions: getValueFromPlist(java.io.File, java.lang.String), setValueForPlist(java.io.File, java.lang.String, java.lang.String), setValueForPlist(java.io.File, java.lang.String, java.util.List), deleteValueFromPlist(java.io.File, java.lang.String)

* Try:
Run with --stacktrace option to get the stack trace. Run with --info or --debug option to get more log output.

BUILD FAILED

Total time: 11.558 secs
```

How can we ignore tests?
Will this "gradle -x test" will be supported here?

Here is the Build script in my build.gradle file
```
buildscript {
        repositories {
                maven {
                        url('http://repository.openbakery.org')
                }
                mavenCentral()
  }

        dependencies {
            classpath "org.openbakery:xcode-plugin:0.14.+"
        }
}

apply plugin: 'org.openbakery.xcode-plugin'
```
I would like to know, why it is upgrading to a develop version?

Thanks & Regards,
Aswini

**Comment by renep** [comment]
try version 0.14.4.develop.71

If this is still not fixed then please run gradle with `--stacktrace` so that I get a hint where the problem is.

**Comment by Aswini999** [comment]
Thanks @renep 

Now 'archive' task passed but package task failed

Here is the error when run with `--stacktrace`
```

$ gradle package/MyApp/Release --stacktrace
:provisioningClean
:provisioningInstall
:cocoapodsInstall
:xcodebuildConfig
:infoplistModify
:xcodebuild
Done
:archive
:keychainClean
:keychainCreate
:package FAILED
:keychainRemove

FAILURE: Build failed with an exception.

* What went wrong:
Execution failed for task ':package'.
> Command failed to run (exit code 1): '/usr/libexec/PlistBuddy -x /var/folders/wp/y8sll_51779d5qbql6z__ft40000gp/T/provision_gradle-e4b59ce1-1115-4971-961a-edf805cf3d6b.plist -c Print Entitlements'
  Tail of output:
  Cannot parse a NULL or zero-length data
  Error Reading File: /var/folders/wp/y8sll_51779d5qbql6z__ft40000gp/T/provision_gradle-e4b59ce1-1115-4971-961a-edf805cf3d6b.plist

* Try:
Run with --info or --debug option to get more log output.

* Exception is:
org.gradle.api.tasks.TaskExecutionException: Execution failed for task ':package'.
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:69)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.execute(ExecuteActionsTaskExecuter.java:46)
        at org.gradle.api.internal.tasks.execution.PostExecutionAnalysisTaskExecuter.execute(PostExecutionAnalysisTaskExecuter.java:35)
        at org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter.execute(SkipUpToDateTaskExecuter.java:64)
        at org.gradle.api.internal.tasks.execution.ValidatingTaskExecuter.execute(ValidatingTaskExecuter.java:58)
        at org.gradle.api.internal.tasks.execution.SkipEmptySourceFilesTaskExecuter.execute(SkipEmptySourceFilesTaskExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipTaskWithNoActionsExecuter.execute(SkipTaskWithNoActionsExecuter.java:52)
        at org.gradle.api.internal.tasks.execution.SkipOnlyIfTaskExecuter.execute(SkipOnlyIfTaskExecuter.java:53)
        at org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter.execute(ExecuteAtMostOnceTaskExecuter.java:43)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:233)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter$EventFiringTaskWorker.execute(DefaultTaskGraphExecuter.java:215)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.processTask(AbstractTaskPlanExecutor.java:74)
        at org.gradle.execution.taskgraph.AbstractTaskPlanExecutor$TaskExecutorWorker.run(AbstractTaskPlanExecutor.java:55)
        at org.gradle.execution.taskgraph.DefaultTaskPlanExecutor.process(DefaultTaskPlanExecutor.java:32)
        at org.gradle.execution.taskgraph.DefaultTaskGraphExecuter.execute(DefaultTaskGraphExecuter.java:113)
        at org.gradle.execution.SelectedTaskExecutionAction.execute(SelectedTaskExecutionAction.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.access$000(DefaultBuildExecuter.java:23)
        at org.gradle.execution.DefaultBuildExecuter$1.proceed(DefaultBuildExecuter.java:43)
        at org.gradle.execution.DryRunBuildExecutionAction.execute(DryRunBuildExecutionAction.java:32)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:37)
        at org.gradle.execution.DefaultBuildExecuter.execute(DefaultBuildExecuter.java:30)
        at org.gradle.initialization.DefaultGradleLauncher$4.run(DefaultGradleLauncher.java:186)
        at org.gradle.internal.Factories$1.create(Factories.java:22)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:53)
        at org.gradle.initialization.DefaultGradleLauncher.doBuildStages(DefaultGradleLauncher.java:183)
        at org.gradle.initialization.DefaultGradleLauncher.access$200(DefaultGradleLauncher.java:33)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:112)
        at org.gradle.initialization.DefaultGradleLauncher$1.create(DefaultGradleLauncher.java:106)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:91)
        at org.gradle.internal.progress.DefaultBuildOperationExecutor.run(DefaultBuildOperationExecutor.java:63)
        at org.gradle.initialization.DefaultGradleLauncher.doBuild(DefaultGradleLauncher.java:106)
        at org.gradle.initialization.DefaultGradleLauncher.run(DefaultGradleLauncher.java:92)
        at org.gradle.launcher.exec.GradleBuildController.run(GradleBuildController.java:66)
        at org.gradle.tooling.internal.provider.ExecuteBuildActionRunner.run(ExecuteBuildActionRunner.java:28)
        at org.gradle.launcher.exec.ChainingBuildActionRunner.run(ChainingBuildActionRunner.java:35)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:41)
        at org.gradle.launcher.exec.InProcessBuildActionExecuter.execute(InProcessBuildActionExecuter.java:26)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:79)
        at org.gradle.tooling.internal.provider.ContinuousBuildActionExecuter.execute(ContinuousBuildActionExecuter.java:51)
        at org.gradle.launcher.daemon.server.exec.ExecuteBuild.doBuild(ExecuteBuild.java:59)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.WatchForDisconnection.execute(WatchForDisconnection.java:47)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ResetDeprecationLogger.execute(ResetDeprecationLogger.java:26)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.RequestStopIfSingleUsedDaemon.execute(RequestStopIfSingleUsedDaemon.java:34)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:74)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput$2.call(ForwardClientInput.java:72)
        at org.gradle.util.Swapper.swap(Swapper.java:38)
        at org.gradle.launcher.daemon.server.exec.ForwardClientInput.execute(ForwardClientInput.java:72)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogAndCheckHealth.execute(LogAndCheckHealth.java:55)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.LogToClient.doBuild(LogToClient.java:60)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.EstablishBuildEnvironment.doBuild(EstablishBuildEnvironment.java:72)
        at org.gradle.launcher.daemon.server.exec.BuildCommandOnly.execute(BuildCommandOnly.java:36)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.HintGCAfterBuild.execute(HintGCAfterBuild.java:44)
        at org.gradle.launcher.daemon.server.api.DaemonCommandExecution.proceed(DaemonCommandExecution.java:120)
        at org.gradle.launcher.daemon.server.exec.StartBuildOrRespondWithBusy$1.run(StartBuildOrRespondWithBusy.java:50)
        at org.gradle.launcher.daemon.server.DaemonStateCoordinator$1.run(DaemonStateCoordinator.java:293)
        at org.gradle.internal.concurrent.ExecutorPolicy$CatchAndRecordFailures.onExecute(ExecutorPolicy.java:54)
        at org.gradle.internal.concurrent.StoppableExecutorImpl$1.run(StoppableExecutorImpl.java:40)
Caused by: org.openbakery.CommandRunnerException: Command failed to run (exit code 1): '/usr/libexec/PlistBuddy -x /var/folders/wp/y8sll_51779d5qbql6z__ft40000gp/T/provision_gradle-e4b59ce1-1115-4971-961a-edf805cf3d6b.plist -c Print Entitlements'
Tail of output:
Cannot parse a NULL or zero-length data
Error Reading File: /var/folders/wp/y8sll_51779d5qbql6z__ft40000gp/T/provision_gradle-e4b59ce1-1115-4971-961a-edf805cf3d6b.plist
        at org.openbakery.CommandRunner.run(CommandRunner.groovy:97)
        at org.openbakery.CommandRunner$run$2.callCurrent(Unknown Source)
        at org.openbakery.CommandRunner.runWithResult(CommandRunner.groovy:187)
        at org.openbakery.CommandRunner$runWithResult$1.callCurrent(Unknown Source)
        at org.openbakery.CommandRunner.runWithResult(CommandRunner.groovy:182)
        at org.openbakery.CommandRunner$runWithResult$0.callCurrent(Unknown Source)
        at org.openbakery.CommandRunner.runWithResult(CommandRunner.groovy:178)
        at org.openbakery.CommandRunner$runWithResult.call(Unknown Source)
        at org.openbakery.codesign.ProvisioningProfileReader.extractEntitlements(ProvisioningProfileReader.groovy:201)
        at org.openbakery.codesign.ProvisioningProfileReader$extractEntitlements$3.call(Unknown Source)
        at org.openbakery.codesign.Codesign.createEntitlementsFile(Codesign.groovy:143)
        at org.openbakery.codesign.Codesign$createEntitlementsFile$0.callCurrent(Unknown Source)
        at org.openbakery.codesign.Codesign.sign(Codesign.groovy:51)
        at org.openbakery.codesign.Codesign$sign.call(Unknown Source)
        at org.openbakery.packaging.PackageTask.packageApplication(PackageTask.groovy:101)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:136)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:129)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:118)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:623)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:606)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
        ... 68 more


BUILD FAILED

Total time: 13.396 secs
```

**Comment by Aswini999** [comment]
@renep , Kindly let us know if this change impacted Package issue? We are waiting for this fix. Please suggest ASAP

Regards,
Aswini

**Comment by renep** [comment]
Have you tried the 0.14.3 stable version if it has this issue. I have done a lot of refactoring in 0.14.4.develop and this can be one of the things I have missed, or the unit tests ;-)

**Comment by Aswini999** [comment]
I have tried with 0.14.3 also. It has problem with Package task. 

https://github.com/openbakery/gradle-xcodePlugin/issues/301

Also When I tried with build script given in previous comment, it is upgraded to develop version.
But the package problem is fixed with same build.gradle before it is upgraded to "0.14.4.develop.70"

Kindly help to fix.

**Comment by renep** [comment]
So it did work with version`0.14.4.develop.69`?

**Comment by Aswini999** [comment]
Yes @renep

**Comment by renep** [comment]
Have added that then the entitlements is not found that no exception is thrown. I don't know if this fixes this issue. If not, then run gradle with '--debug' or  '-i' and post the log to see whats wrong.

So please test version `0.14.4.develop.72` (this version should be deployed in a few minutes)

When using `classpath "org.openbakery:xcode-plugin:0.14.+"` you should not get the latest develop version. 
To make sure you only get the latest stable use the settings from plugins.gradle.org: https://plugins.gradle.org/plugin/org.openbakery.xcode-plugin

The develop versions are only deployed in repository.openbakery.org.

The plist path has changed from the `build` directory to `tmp`. The reason for this is that I extract the stuff that is not gradle depended into a own lib and here the build directory is unknown.
