### ISSUE TITLE
Division undefined error in Coverage

### ISSUE THREAD

**Issue by davetrux** [openbakery/gradle-xcodePlugin#349]
Since upgrading to Xcode 8.3.1 the coverage task fails with a Division undefined error:

```
Caused by: java.lang.ArithmeticException: Division undefined
        at org.openbakery.coverage.model.SourceFile.getCoverage(SourceFile.groovy:138)
        at org.openbakery.coverage.model.SourceFile$getCoverage$2.call(Unknown Source)
        at org.openbakery.coverage.report.ReportData.getData(ReportData.groovy:91)
        at org.openbakery.coverage.report.XMLReport.generate(XMLReport.groovy:27)
        at org.openbakery.coverage.report.XMLReport$generate.call(Unknown Source)
        at org.openbakery.coverage.Report.createReport(Report.groovy:149)
        at org.openbakery.coverage.Report.create(Report.groovy:111)
        at org.openbakery.coverage.Report$create$1.callCurrent(Unknown Source)
        at org.openbakery.coverage.Report.create(Report.groovy:76)
        at org.openbakery.coverage.Report$create$0.call(Unknown Source)
        at org.openbakery.coverage.CoverageTask.coverage(CoverageTask.groovy:46)
        at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:73)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.doExecute(DefaultTaskClassInfoStore.java:141)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:134)
        at org.gradle.api.internal.project.taskfactory.DefaultTaskClassInfoStore$StandardTaskAction.execute(DefaultTaskClassInfoStore.java:123)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:632)
        at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:615)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:95)
        at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:76)
        ... 70 more
```
It seems like the lines covered and lines executed are no longer being generated or pulled from the coverage report? 

All of our projects are experiencing this.

**Comment by renep** [comment]
I have create a Issue in the proper project: https://github.com/openbakery/CoverageReport/issues/3

I think this should not be a big issue, but I'm quite busy right now, so I don't know when I find time to fix this.

**Comment by pnwaterloo** [comment]
@renep  Just wondering if you have any updates? Xcode v 8.3.2 & 8.3.3 are both giving "division undefined" error. 
Execution failed for task ':coverage'
> Disivion Undefined

**Comment by pnwaterloo** [comment]
@renep I noticed the PR for this issue was submitted successfully. I was wondering if a new release can be created for XCode

**Comment by renep** [comment]
see https://github.com/openbakery/CoverageReport/issues/3#issuecomment-322996750

**Comment by eugenious** [comment]
When do you think the next version of the xcode plugin will be released, that includes this fix?
