### ISSUE TITLE
Plugin fails to resolve bundle name when PRODUCT_NAME contains $(TARGET_NAME:c99extidentifier)

### ISSUE THREAD

**Issue by phatblat** [openbakery/gradle-xcodePlugin#361]
Playing around with an Xcode project generated by SPM and hit this snag. The Info.plist file (which gets put inside the .xcodeproj bundle) contains `$(PRODUCT_NAME)` for `CFBundleIdentifier`. When the plugin goes to resolve `PRODUCT_NAME` it chokes due to the value being outside of the short list of things in [`VariableResolver`](https://github.com/openbakery/gradle-xcodePlugin/blob/860edafdc63bc4fc9a7058b73501fc8835c6ec7e/plugin/src/main/groovy/org/openbakery/util/VariableResolver.groovy#L54-L56).

- `PRODUCT_NAME = $(TARGET_NAME:c99extidentifier)`

```
Caused by: java.lang.IllegalArgumentException: Illegal group reference
        at java_lang_String$replaceAll$4.call(Unknown Source)
        at org.openbakery.util.VariableResolver$_resolveCurlyBrackets_closure1.doCall(VariableResolver.groovy:26)
        at org.openbakery.util.VariableResolver.resolveCurlyBrackets(VariableResolver.groovy:24)
        at org.openbakery.util.VariableResolver.resolve(VariableResolver.groovy:48)
        at org.openbakery.util.VariableResolver$resolve.call(Unknown Source)
        at org.openbakery.XcodeBuildPluginExtension.getBundleName(XcodeBuildPluginExtension.groovy:322)
        at org.openbakery.XcodeBuildPluginExtension_Decorated.getBundleName(Unknown Source)
        at org.openbakery.XcodeBuildPluginExtension.getApplicationBundle(XcodeBuildPluginExtension.groovy:375)
        at org.openbakery.XcodeBuildPluginExtension_Decorated.getApplicationBundle(Unknown Source)
        at org.openbakery.XcodeBuildPluginExtension.getXcodebuildParameters(XcodeBuildPluginExtension.groovy:488)
        at org.openbakery.XcodeBuildPluginExtension_Decorated.getXcodebuildParameters(Unknown Source)
        at org.gradle.internal.metaobject.BeanDynamicObject$MetaClassAdapter.getProperty(BeanDynamicObject.java:213)
        at org.gradle.internal.metaobject.BeanDynamicObject.getProperty(BeanDynamicObject.java:156)
        at org.gradle.internal.metaobject.CompositeDynamicObject.getProperty(CompositeDynamicObject.java:55)
        at org.gradle.internal.metaobject.AbstractDynamicObject.getProperty(AbstractDynamicObject.java:60)
        at org.openbakery.XcodeBuildPluginExtension_Decorated.getProperty(Unknown Source)
        at org.openbakery.XcodeBuildTask.build(XcodeBuildTask.groovy:36)
```

Annoying, but easy to work around.

## Workarounds

- Change `PRODUCT_NAME` to just `$(TARGET_NAME)`
- Set `xcodebuild.bundleName` in `build.gradle`

**Comment by jimadamsss** [comment]
Has this change actually made it into the product? I seem to be failing at the exact line:
Caused by: java.lang.IllegalArgumentException: Illegal group reference
  at java_lang_String$replaceAll$3.call(Unknown Source)
  at org.openbakery.util.VariableResolver$_resolve_closure1.doCall(VariableResolver.groovy:49)
  at org.openbakery.util.VariableResolver.resolve(VariableResolver.groovy:39)
  at org.openbakery.util.VariableResolver$resolve.call(Unknown Source)
  at org.openbakery.XcodeBuildPluginExtension.getBundleName(XcodeBuildPluginExtension.groovy:322)

As far as I can tell I have the TARGET_NAME:c99extidentifier for my target. I see this with 0.15.2 and 0.19.1

**Comment by renep** [comment]
Yes this issue was added in Version 0.15.3 and should still be in the current version.
