### ISSUE TITLE
hockey provisioning_profiles upload failed

### ISSUE THREAD

**Issue by renep** [openbakery/gradle-xcodePlugin#76]
From #48
https://github.com/openbakery/gradle-xcodePlugin/issues/48#issuecomment-51602568

Thanks René for the fast reply.

The upload is done correctly. I see the new version on hockeyapp and can install it.
The problem is that the gradle script still generates the error.

Just to confirm, the build doesn't fail, the ipa and dsym (zipped) are on the hockeyapp folder
The API token is correct.

Here is the part of the complete log that includes everything related to hockeyapp.

Thanks!

```
15:40:36.799 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :hockeyapp-prepare (Thread[main,5,main]) started.
15:40:36.799 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :hockeyapp-prepare
15:40:36.800 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':hockeyapp-prepare'
15:40:36.800 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':hockeyapp-prepare' is up-to-date
15:40:36.801 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':hockeyapp-prepare' (up-to-date check took 0.0010 secs) due to:
  Task has not declared any outputs.
15:40:36.801 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':hockeyapp-prepare'.
15:40:36.810 [DEBUG] [org.gradle.api.Task] project.hockeyapp.outputDirectory /Users/user/Projects/sdk-ios-v2/testapp-static/build/hockeyapp
15:40:36.811 [DEBUG] [org.gradle.api.Task] baseZipName iOSSDKTest
15:40:36.811 [DEBUG] [org.gradle.api.Task] buildOutputDirectory /Users/user/Projects/sdk-ios-v2/testapp-static/build/sym/Testing-iphoneos
15:40:37.021 [QUIET] [system.out]       [zip] Building zip: /Users/user/Projects/sdk-ios-v2/testapp-static/build/hockeyapp/iOSSDKTest.app.dSYM.zip
15:40:38.334 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':hockeyapp-prepare'
15:40:38.334 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :hockeyapp-prepare (Thread[main,5,main]) completed. Took 1.535 secs.
15:40:38.335 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :hockeyapp (Thread[main,5,main]) started.
15:40:38.335 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :hockeyapp
15:40:38.335 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Starting to execute task ':hockeyapp'
15:40:38.335 [DEBUG] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Determining if task ':hockeyapp' is up-to-date
15:40:38.336 [INFO] [org.gradle.api.internal.tasks.execution.SkipUpToDateTaskExecuter] Executing task ':hockeyapp' (up-to-date check took 0.0 secs) due to:
  Task has not declared any outputs.
15:40:38.336 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter] Executing actions for task ':hockeyapp'.
15:40:38.342 [DEBUG] [org.gradle.api.Task] ipaFile: /Users/user/Projects/sdk-ios-v2/testapp-static/build/hockeyapp/iOSSDKTest.ipa
15:40:38.342 [DEBUG] [org.gradle.api.Task] dSYMFile: /Users/user/Projects/sdk-ios-v2/testapp-static/build/hockeyapp/iOSSDKTest.app.dSYM.zip
15:40:38.342 [DEBUG] [org.gradle.api.Task] api_token: [removed hockeyapp api token]
15:40:38.343 [DEBUG] [org.gradle.api.Task] notes: Testing from gradle 
15:40:38.344 [DEBUG] [org.gradle.api.Task] file: /Users/user/Projects/sdk-ios-v2/testapp-static/build/hockeyapp/iOSSDKTest.ipa 
15:40:38.344 [DEBUG] [org.gradle.api.Task] dsym: /Users/user/Projects/sdk-ios-v2/testapp-static/build/hockeyapp/iOSSDKTest.app.dSYM.zip 
15:40:38.344 [DEBUG] [org.gradle.api.Task] status: 2 
15:40:38.344 [DEBUG] [org.gradle.api.Task] notify: 0 
15:40:38.345 [DEBUG] [org.gradle.api.Task] notes_type: 1 
15:40:38.408 [DEBUG] [org.gradle.api.Task] request POST https://rink.hockeyapp.net/api/2/apps/[removed hockeyapp app id]/app_versions/upload HTTP/1.1
15:40:38.637 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Get connection for route {s}->https://rink.hockeyapp.net
15:40:38.833 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator] Connecting to rink.hockeyapp.net:443
15:40:39.407 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: best-match
15:40:39.420 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
15:40:39.421 [DEBUG] [org.apache.http.client.protocol.RequestTargetAuthentication] Target auth state: UNCHALLENGED
15:40:39.422 [DEBUG] [org.apache.http.client.protocol.RequestProxyAuthentication] Proxy auth state: UNCHALLENGED
15:40:39.422 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Attempt 1 to execute request
15:40:39.423 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending request: POST /api/2/apps/[removed hockeyapp app id]/app_versions/upload HTTP/1.1
15:40:39.424 [DEBUG] [org.apache.http.headers] >> POST /api/2/apps/[removed hockeyapp app id]/app_versions/upload HTTP/1.1
15:40:39.424 [DEBUG] [org.apache.http.headers] >> X-HockeyAppToken: [removed hockeyapp api token]
15:40:39.425 [DEBUG] [org.apache.http.headers] >> Content-Length: 21203751
15:40:39.425 [DEBUG] [org.apache.http.headers] >> Content-Type: multipart/form-data; boundary=CXotL6F1Ka3VrkPPN93hIqUUkR9EL9uK
15:40:39.425 [DEBUG] [org.apache.http.headers] >> Host: rink.hockeyapp.net
15:40:39.425 [DEBUG] [org.apache.http.headers] >> Connection: Keep-Alive
15:40:39.425 [DEBUG] [org.apache.http.headers] >> User-Agent: Apache-HttpClient/4.2.6 (java 1.5)
15:41:16.258 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Receiving response: HTTP/1.1 201 Created
15:41:16.258 [DEBUG] [org.apache.http.headers] << HTTP/1.1 201 Created
15:41:16.258 [DEBUG] [org.apache.http.headers] << Cache-Control: max-age=0, private, must-revalidate
15:41:16.258 [DEBUG] [org.apache.http.headers] << Content-Type: text/html; charset=utf-8
15:41:16.259 [DEBUG] [org.apache.http.headers] << Date: Fri, 08 Aug 2014 13:41:15 GMT
15:41:16.259 [DEBUG] [org.apache.http.headers] << ETag: "89702c3cb06512ddf8ff146bea3efecc"
15:41:16.259 [DEBUG] [org.apache.http.headers] << Server: nginx
15:41:16.259 [DEBUG] [org.apache.http.headers] << Set-Cookie: request_method=POST; path=/
15:41:16.260 [DEBUG] [org.apache.http.headers] << Status: 201 Created
15:41:16.260 [DEBUG] [org.apache.http.headers] << X-Rack-Cache: invalidate, pass
15:41:16.260 [DEBUG] [org.apache.http.headers] << X-Request-Id: 4e6ada76dbdd1d04fb8ec10f738fe983
15:41:16.260 [DEBUG] [org.apache.http.headers] << X-Runtime: 3.777481
15:41:16.260 [DEBUG] [org.apache.http.headers] << X-UA-Compatible: IE=Edge,chrome=1
15:41:16.260 [DEBUG] [org.apache.http.headers] << Content-Length: 847
15:41:16.260 [DEBUG] [org.apache.http.headers] << Connection: keep-alive
15:41:16.267 [DEBUG] [org.apache.http.client.protocol.ResponseProcessCookies] Cookie accepted: "[version: 0][name: request_method][value: POST][domain: rink.hockeyapp.net][path: /][expiry: null]". 
15:41:16.269 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Connection can be kept alive indefinitely
15:41:16.274 [DEBUG] [org.gradle.api.Task] request POST https://rink.hockeyapp.net/api/2/apps/[removed hockeyapp app id]/provisioning_profiles HTTP/1.1
15:41:16.281 [DEBUG] [org.apache.http.impl.conn.BasicClientConnectionManager] Get connection for route {s}->https://rink.hockeyapp.net
15:41:16.282 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnectionOperator] Connecting to rink.hockeyapp.net:443
15:41:16.722 [DEBUG] [org.apache.http.client.protocol.RequestAddCookies] CookieSpec selected: best-match
15:41:16.723 [DEBUG] [org.apache.http.client.protocol.RequestAuthCache] Auth cache not set in the context
15:41:16.723 [DEBUG] [org.apache.http.client.protocol.RequestTargetAuthentication] Target auth state: UNCHALLENGED
15:41:16.723 [DEBUG] [org.apache.http.client.protocol.RequestProxyAuthentication] Proxy auth state: UNCHALLENGED
15:41:16.724 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Attempt 1 to execute request
15:41:16.724 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Sending request: POST /api/2/apps/[removed hockeyapp app id]/provisioning_profiles HTTP/1.1
15:41:16.724 [DEBUG] [org.apache.http.headers] >> POST /api/2/apps/[removed hockeyapp app id]/provisioning_profiles HTTP/1.1
15:41:16.725 [DEBUG] [org.apache.http.headers] >> X-HockeyAppToken: [removed hockeyapp api token]
15:41:16.725 [DEBUG] [org.apache.http.headers] >> Content-Length: 9187
15:41:16.725 [DEBUG] [org.apache.http.headers] >> Content-Type: multipart/form-data; boundary=nlggrRDWNTG_UsojQtKHBC0UjBFMHn
15:41:16.725 [DEBUG] [org.apache.http.headers] >> Host: rink.hockeyapp.net
15:41:16.726 [DEBUG] [org.apache.http.headers] >> Connection: Keep-Alive
15:41:16.726 [DEBUG] [org.apache.http.headers] >> User-Agent: Apache-HttpClient/4.2.6 (java 1.5)
15:41:16.954 [DEBUG] [org.apache.http.impl.conn.DefaultClientConnection] Receiving response: HTTP/1.1 400 Bad Request
15:41:16.955 [DEBUG] [org.apache.http.headers] << HTTP/1.1 400 Bad Request
15:41:16.955 [DEBUG] [org.apache.http.headers] << Cache-Control: no-cache
15:41:16.955 [DEBUG] [org.apache.http.headers] << Content-Type: text/html; charset=utf-8
15:41:16.955 [DEBUG] [org.apache.http.headers] << Date: Fri, 08 Aug 2014 13:41:16 GMT
15:41:16.956 [DEBUG] [org.apache.http.headers] << Server: nginx
15:41:16.956 [DEBUG] [org.apache.http.headers] << Set-Cookie: request_method=POST; path=/
15:41:16.956 [DEBUG] [org.apache.http.headers] << Status: 400 Bad Request
15:41:16.957 [DEBUG] [org.apache.http.headers] << X-Rack-Cache: invalidate, pass
15:41:16.957 [DEBUG] [org.apache.http.headers] << X-Request-Id: 515e85dfd7d4eb53305d30e811ffe4ca
15:41:16.957 [DEBUG] [org.apache.http.headers] << X-Runtime: 0.020576
15:41:16.958 [DEBUG] [org.apache.http.headers] << X-UA-Compatible: IE=Edge,chrome=1
15:41:16.958 [DEBUG] [org.apache.http.headers] << Content-Length: 65
15:41:16.958 [DEBUG] [org.apache.http.headers] << Connection: keep-alive
15:41:16.959 [DEBUG] [org.apache.http.client.protocol.ResponseProcessCookies] Cookie accepted: "[version: 0][name: request_method][value: POST][domain: rink.hockeyapp.net][path: /][expiry: null]". 
15:41:16.959 [DEBUG] [org.apache.http.impl.client.DefaultHttpClient] Connection can be kept alive indefinitely
15:41:16.962 [DEBUG] [org.gradle.api.internal.tasks.execution.ExecuteAtMostOnceTaskExecuter] Finished executing task ':hockeyapp'
15:41:16.963 [LIFECYCLE] [class org.gradle.TaskExecutionLogger] :hockeyapp FAILED
15:41:16.963 [INFO] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] :hockeyapp (Thread[main,5,main]) completed. Took 38.628 secs.
15:41:16.964 [DEBUG] [org.gradle.execution.taskgraph.AbstractTaskPlanExecutor] Task worker [Thread[main,5,main]] finished, busy: 1 mins 50.247 secs, idle: 0.013 secs
15:41:16.969 [ERROR] [org.gradle.BuildExceptionReporter] 
15:41:16.970 [ERROR] [org.gradle.BuildExceptionReporter] FAILURE: Build failed with an exception.
15:41:16.971 [ERROR] [org.gradle.BuildExceptionReporter] 
15:41:16.971 [ERROR] [org.gradle.BuildExceptionReporter] * What went wrong:
15:41:16.971 [ERROR] [org.gradle.BuildExceptionReporter] Execution failed for task ':hockeyapp'.
15:41:16.971 [ERROR] [org.gradle.BuildExceptionReporter] > file upload failed: 400 Bad Request
15:41:16.972 [ERROR] [org.gradle.BuildExceptionReporter] 
15:41:16.972 [ERROR] [org.gradle.BuildExceptionReporter] * Try:
15:41:16.972 [ERROR] [org.gradle.BuildExceptionReporter] Run with --stacktrace option to get the stack trace. 
15:41:16.973 [LIFECYCLE] [org.gradle.BuildResultLogger] 
15:41:16.974 [LIFECYCLE] [org.gradle.BuildResultLogger] BUILD FAILED
15:41:16.974 [LIFECYCLE] [org.gradle.BuildResultLogger] 
15:41:16.974 [LIFECYCLE] [org.gradle.BuildResultLogger] Total time: 1 mins 55.482 secs
15:41:16.978 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on buildscript class cache for build file '/Users/user/Projects/sdk-ios-v2/testapp-static/build.gradle' (/Users/user/.gradle/caches/2.0/scripts/build_3g3amv0ln496koaecdsqnfvpid/ProjectScript/buildscript).
15:41:16.978 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on no_buildscript class cache for build file '/Users/user/Projects/sdk-ios-v2/testapp-static/build.gradle' (/Users/user/.gradle/caches/2.0/scripts/build_3g3amv0ln496koaecdsqnfvpid/ProjectScript/no_buildscript).
15:41:16.981 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache artifact-at-repository.bin (/Users/user/.gradle/caches/modules-2/metadata-2.12/artifact-at-repository.bin)
15:41:16.981 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-metadata.bin (/Users/user/.gradle/caches/modules-2/metadata-2.12/module-metadata.bin)
15:41:16.982 [DEBUG] [org.gradle.cache.internal.btree.BTreePersistentIndexedCache] Closing cache module-versions.bin (/Users/user/.gradle/caches/modules-2/metadata-2.12/module-versions.bin)
15:41:16.982 [DEBUG] [org.gradle.cache.internal.DefaultFileLockManager] Releasing lock on artifact cache (/Users/user/.gradle/caches/modules-2).
15:41:16.987 [DEBUG] [org.gradle.cache.internal.DefaultCacheAccess] Cache task history cache (/Users/user/Projects/sdk-ios-v2/testapp-static/.gradle/2.0/taskArtifacts) was closed 0 times.
15:41:16.989 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.ivyresolve.memcache.InMemoryCachedRepositoryFactory] In-memory dependency metadata cache closed. Repos cached: 2, cache instances: 2, modules served from cache: 0, artifacts: 0
15:41:16.991 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolution result cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
15:41:16.991 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.CachedStoreFactory] Resolved configuration cache closed. Cache reads: 0, disk reads: 0 (avg: 0.0 secs, total: 0.0 secs)
15:41:16.992 [DEBUG] [org.gradle.api.internal.artifacts.ivyservice.resolveengine.store.ResolutionResultsStoreFactory] Deleted 2 resolution results binary files in 0.0010 secs
```

**Comment by karnett** [comment]
I am also retrieving this build failed, 422, mobile provision error, with a successful upload to hockey app. Maybe there's something in our .gradle hockey app settings that's wrong.

`gradle archive package hockeyapp --stacktrace`

...
`	at org.openbakery.hockeyapp.HockeyAppUploadTask.uploadProvisioningProfile(HockeyAppUploadTask.groovy:144)
	at org.openbakery.hockeyapp.HockeyAppUploadTask.upload(HockeyAppUploadTask.groovy:82)
	at org.gradle.internal.reflect.JavaMethod.invoke(JavaMethod.java:75)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.doExecute(AnnotationProcessingTaskFactory.java:227)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:220)
	at org.gradle.api.internal.project.taskfactory.AnnotationProcessingTaskFactory$StandardTaskAction.execute(AnnotationProcessingTaskFactory.java:209)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:585)
	at org.gradle.api.internal.AbstractTask$TaskActionWrapper.execute(AbstractTask.java:568)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeAction(ExecuteActionsTaskExecuter.java:80)
	at org.gradle.api.internal.tasks.execution.ExecuteActionsTaskExecuter.executeActions(ExecuteActionsTaskExecuter.java:61)
`

**Comment by renep** [comment]
I'm wondering. I have tested the hockeyapp upload myself with the example app and I had no problem:
https://github.com/openbakery/gradle-xcodePlugin/tree/master/example/iOS/Example

Maybe there is something wrong with your sign settings and hockeyapp does some validation here. Have you tried to manually install the ipa on your device that is created with the `package` task if it works?

**Comment by karnett** [comment]
Allllright. So this is what I found to be the issue, definitely in hockey app, but I'm spilling it here for anyone else that encounters such an issue. If you have manually uploaded a build to hockey app, prior to using the script to upload, there is a difference in the provisioning profiles (if you look at them, ones xml, ones garbage characters). And apparently its that conflict that throws the error back. It'd be nice if the build didn't fail for that error, since it successfully uploads, but I'm not sure that's a good use case either.

**Comment by fdubuisson** [comment]
Fyi, we encounter the same error when using different provisionings for builds.
In our project, we provide builds for 2 different accounts, with 2 different certificate/provisioning. If we do 2 builds without cleaning everything in between, we have this error. With a clean, no more error.
Not sure this should be handled by the plugin, though...

**Comment by jonathanff** [comment]
I have the same issue and received an email from hockey app that it was successfully uploaded but when I go the Hockey app dashboard the build is not present. Any clue?
